name: Build
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install toolchain
        uses: numworks/setup-arm-toolchain@2020-q2
      - name: Run make build
        run: make build
      - name: Run make check
        run: make check
